spring:
  application:
    name: api
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      repositories:
        enabled: false

server:
  port: 8080
