spring:
  datasource:
    url: jdbc:mariadb://localhost:${MARIADB_PORT:13306}/${MYSQL_DATABASE:swucjute_local}
    username: ${DB_USER:swucjute}
    password: ${DB_PASSWORD:swucjute12!@}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:16379}
    mongodb:
      host: localhost
      port: ${MONGODB_PORT:27017}
      database: swucjute_files
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:swucjute12!@}
      authentication-database: admin

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    com.swucjute.api: DEBUG
    org.hibernate.SQL: DEBUG
